databases:
  - name: calendar-mcp-db
    databaseName: calendar_mcp
    user: calendar_mcp_user
    plan: free

services:
  - type: web
    name: calendar-mcp-server
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: calendar-mcp-db
          property: connectionString
      - key: CALENDAR_MCP_SERVER_API_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11"
    autoDeploy: false

  - type: web
    name: calendar-mcp-admin
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn admin_app.app:app"
    healthCheckPath: /login
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: calendar-mcp-db
          property: connectionString
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
    autoDeploy: false

