# render.yaml
# Blueprint for deploying the FastMCP 2.0 Server, Web Admin App, and Postgres DB on Render.com

# Render free plan allows only 1 database so this is generic for all apps
databases:
  - name: app-db # Name of your database service
    databaseName: app-db # Name of the actual database
    user: app_user # Username for the database
    plan: free

services:
  - type: web
    name: joke-mcp-server # FastMCP 2.0 server
    env: python    
    plan: free 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py" # FastMCP handles its own server run    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app-db
          property: connectionString
      - key: JOKE_MCP_SERVER_API_KEY 
        sync: false  # This needs to be set manually in the Render dashboard

  - type: web
    name: joke-mcp-web-app # Flask web app
    env: python    
    plan: free 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn joke_mcp_web_app.app:app --bind 0.0.0.0:$PORT"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app-db  
          property: connectionString
      - key: FLASK_SECRET_KEY 
        generateValue: true
      - key: FLASK_APP 
        value: "joke_mcp_web_app.app:app"
      - key: JOKE_MCP_SERVER_API_KEY 
        sync: false  # This needs to be set manually in the Render dashboard        
      - key: ADMIN_EMAIL
        sync: false  # This needs to be set manually in the Render dashboard
      - key: ADMIN_PASSWORD
        sync: false  # This needs to be set manually in the Render dashboard

